version: "2"
services:
  boilerplate-api:
    build: .
    environment:
      - MONGO_URI=mongodb://mongodb-angel:27017/rr
    volumes:
      - .:/app
    ports:
      - "5000:5000"
    depends_on:
      - mongodb-angel

  mongodb-angel:
    image: mongo
    ports:
      - "27017:27017"
